/**
 * Legacy SKUs (pre-2026-09 `ABC-123` format) -> current SKUs. Old links and
 * QR codes (`?sku=BAG-001`) must keep resolving; consulted by
 * `getProductBySku` only — never referenced by product content.
 * Generated by scripts/migrate-skus-categories.js; edit by hand only to add
 * future aliases.
 * @type {Record<string, string>}
 */
export const skuAliases = {
	'ACC-001': 'AAA000023',
	'BAG-001': 'AAA000001',
	'BAG-002': 'AAA000002',
	'BAG-003': 'AAA000003',
	'BAG-004': 'AAA000004',
	'BAG-005': 'AAA000005',
	'BAG-006': 'AAA000006',
	'BAG-007': 'AAA000007',
	'BAG-008': 'AAA000026',
	'BEAD-001': 'AAA000032',
	'BEAD-002': 'AAA000033',
	'BEAD-003': 'AAA000034',
	'BEAD-004': 'AAA000035',
	'BEAD-005': 'AAA000036',
	'BEAD-006': 'AAA000037',
	'BEAD-007': 'AAA000038',
	'BEAD-008': 'AAA000024',
	'BEAD-009': 'AAA000025',
	'BR-001': 'AAA000008',
	'BR-003': 'AAA000009',
	'BR-004': 'AAA000010',
	'BR-005': 'AAA000011',
	'BR-006': 'AAA000012',
	'BR-007': 'AAA000013',
	'BR-008': 'AAA000014',
	'BR-009': 'AAA000015',
	'BR-010': 'AAA000016',
	'BR-011': 'AAA000017',
	'BR-012': 'AAA000018',
	'BR-013': 'AAA000019',
	'BR-014': 'AAA000020',
	'BR-015': 'AAA000021',
	'JWL-001': 'AAA000039',
	'JWL-002': 'AAA000040',
	'JWL-003': 'AAA000041',
	'JWL-004': 'AAA000022',
	'KNIT-001': 'AAA000027',
	'KNIT-002': 'AAA000028',
	'KNIT-003': 'AAA000029',
	'KNIT-004': 'AAA000030',
	'KNIT-005': 'AAA000031',
	'OTH-001': 'AAA000042',
	'OTH-002': 'AAA000043',
	'OTH-003': 'AAA000044'
};
